//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyJob
    {
        public System.Guid ApplyId { get; set; }
        public Nullable<System.Guid> JobId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
    
        public virtual JobDesc JobDesc { get; set; }
        public virtual User User { get; set; }
    }
}
