//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.JobDescs = new HashSet<JobDesc>();
        }
    
        public System.Guid ComapanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyContactNo { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyDesc { get; set; }
        public string CompanyBranchAddr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobDesc> JobDescs { get; set; }
    }
}
