//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCategory
    {
        public string CategoryName { get; set; }
        public string CategoryDesc { get; set; }
        public decimal CategoryId { get; set; }
    }
}
