//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobCategory()
        {
            this.JobDescs = new HashSet<JobDesc>();
        }
    
        public string CategoryName { get; set; }
        public string CategoryDesc { get; set; }
        public int CategoryId { get; set; }
        public string CategoryIcon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobDesc> JobDescs { get; set; }
    }
}
