//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDesc
    {
        public System.Guid JobId { get; set; }
        public string JobName { get; set; }
        public Nullable<System.Guid> ComapanyId { get; set; }
        public string JobType { get; set; }
        public string ExpextedSalary { get; set; }
        public string JobLoc { get; set; }
        public string JobDesc1 { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string JobPos { get; set; }
        public string MinQulafication { get; set; }
        public string JobSkill { get; set; }
    
        public virtual JobCategory JobCategory { get; set; }
    }
}
