//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ApplyJobs = new HashSet<ApplyJob>();
        }
    
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string UserContactNo { get; set; }
        public string UserEmail { get; set; }
        public string Addr { get; set; }
        public string DOB { get; set; }
        public string C10thBoard { get; set; }
        public Nullable<decimal> C10thPercentage { get; set; }
        public string HSBoard { get; set; }
        public Nullable<decimal> HSPercentage { get; set; }
        public string UGUnivercity { get; set; }
        public string UGCollege { get; set; }
        public Nullable<decimal> UGPercentage { get; set; }
        public string PGUniversity { get; set; }
        public string PGCollege { get; set; }
        public Nullable<decimal> PGPercentage { get; set; }
        public string Skill1 { get; set; }
        public string Skill2 { get; set; }
        public string Skill3 { get; set; }
        public string CurrentOfcName { get; set; }
        public string CurrentDesignation { get; set; }
        public string CurrentySalary { get; set; }
        public string TotalYearOfExp { get; set; }
        public string CurrentLoc { get; set; }
        public string Gender { get; set; }
        public string CvPath { get; set; }
        public string AlternatePhno { get; set; }
        public System.DateTime Joinedon { get; set; }
        public string aspnetuserid { get; set; }
        public Nullable<int> C10thpassoutyear { get; set; }
        public Nullable<int> C12thpassoutyear { get; set; }
        public Nullable<int> UGPassoutYear { get; set; }
        public Nullable<int> PGPassoutYear { get; set; }
        public string C10thSchoolName { get; set; }
        public string C12thSchoolName { get; set; }
        public string ProfilePicPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplyJob> ApplyJobs { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
